/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <qle/math/cumulativenormaldistribution.hpp>
#include <qle/math/flatextrapolation.hpp>

