/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <qle/math/flatextrapolation.hpp>
#include <qle/math/piecewisefunction.hpp>
#include <qle/math/piecewiseintegral.hpp>

