/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <qle/math/flatextrapolation.hpp>
#include <qle/math/nadarayawatson.hpp>
#include <qle/math/stabilisedglls.hpp>
#include <qle/math/deltagammavar.hpp>
#include <qle/math/trace.hpp>

