/*
 Copyright (C) 2026 Quaternion Risk Management Ltd
 All rights reserved.

 This file is part of ORE, a free-software/open-source library
 for transparent pricing and risk analysis - http://opensourcerisk.org

 ORE is free software: you can redistribute it and/or modify it
 under the terms of the Modified BSD License.  You should have received a
 copy of the license along with this program.
 The license is also available online at <http://opensourcerisk.org>

 This program is distributed on the basis that it will form a useful
 contribution to risk analytics and model standardisation, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 FITNESS FOR A PARTICULAR PURPOSE. See the license for more details.
*/

#ifndef ored_scriptengine_i
#define ored_scriptengine_i

%{
#include <ored/scripting/scriptparser.hpp>
#include <ored/scripting/ast.hpp>
#include <ored/scripting/astprinter.hpp>
#include <ored/scripting/value.hpp>
#include <ored/scripting/context.hpp>
#include <ored/scripting/scriptengine.hpp>
#include <ored/scripting/paylog.hpp>
#include <ored/scripting/models/model.hpp>
#include <ored/scripting/models/dummymodel.hpp>

using ore::data::LocationInfo;
using ore::data::ASTNode;
using ore::data::ASTNodePtr;
using ore::data::ParserError;
using ore::data::ScriptParser;
using ore::data::EventVec;
using ore::data::CurrencyVec;
using ore::data::IndexVec;
using ore::data::DaycounterVec;
using ore::data::ValueType;
using ore::data::ValueTypeWhich;
using ore::data::Context;
using ore::data::ScriptEngine;
using ore::data::PayLog;
using ore::data::Model;
using ore::data::DummyModel;
%}

%shared_ptr(ore::data::ASTNode)
%shared_ptr(ore::data::Context)
%shared_ptr(ore::data::PayLog)
%shared_ptr(ore::data::Model)
%shared_ptr(ore::data::DummyModel)

// Expose ValueTypeWhich discriminator values as module-level constants
%constant int ValueTypeWhich_Number = 0;
%constant int ValueTypeWhich_Event = 1;
%constant int ValueTypeWhich_Currency = 2;
%constant int ValueTypeWhich_Index = 3;
%constant int ValueTypeWhich_Daycounter = 4;
%constant int ValueTypeWhich_Filter = 5;

%nodefaultctor ore::data::Model;

namespace ore {
namespace data {

// LocationInfo - location within a script
struct LocationInfo {
    LocationInfo();
    LocationInfo(Size lineStart, Size columnStart, Size lineEnd, Size columnEnd);
    bool initialised;
    Size lineStart, columnStart, lineEnd, columnEnd;
};

// ASTNode - Abstract Syntax Tree node (opaque handle)
struct ASTNode {
    LocationInfo locationInfo;
    std::vector<ext::shared_ptr<ASTNode>> args;
};

// ParserError - error information from script parsing
struct ParserError {
    std::string remainingInput;
    LocationInfo stoppedParsingAt;
    std::string expectedWhat;
    LocationInfo expectedWhere;
    std::string scriptCurrentLine;
    std::string scriptContext;
    Size errorPos;
};

// ScriptParser - parses ORE scripting language into an AST
class ScriptParser {
public:
    ScriptParser(const std::string& script);
    bool success() const;
    ext::shared_ptr<ASTNode> ast() const;
    const ParserError& error() const;
};

// ValueTypeWhich - discriminator for ValueType variant
%ignore ore::data::ValueTypeWhich;

// EventVec - represents a date value in the scripting context
struct EventVec {
    Size size;
    Date value;
};

// CurrencyVec - represents a currency value in the scripting context
struct CurrencyVec {
    Size size;
    std::string value;
};

// IndexVec - represents an index name in the scripting context
struct IndexVec {
    Size size;
    std::string value;
};

// DaycounterVec - represents a day counter in the scripting context
struct DaycounterVec {
    Size size;
    std::string value;
};

// Context - holds script variable names and values
struct Context {
    Size varSize() const;
    bool empty() const;
    void resetSize(const std::size_t n);
};

// PayLog - records cashflows generated by PAYLOG() script function
class PayLog {
public:
    PayLog();
    void consolidateAndSort();
    Size size() const;
    const std::vector<Date>& obsDates() const;
    const std::vector<Date>& dates() const;
    const std::vector<std::string>& currencies() const;
    const std::vector<Size>& legNos() const;
    const std::vector<std::string>& cashflowTypes() const;
};

// Model - abstract base for script execution models (opaque, not directly constructible)
class Model {
public:
    virtual ~Model();
};

// DummyModel - testing model that returns placeholder values
class DummyModel : public Model {
public:
    DummyModel(const Size n);
};

// ScriptEngine - executes parsed scripts in a given context
class ScriptEngine {
public:
    ScriptEngine(const ext::shared_ptr<ASTNode> root,
                 const ext::shared_ptr<Context> context,
                 const ext::shared_ptr<Model> model = ext::shared_ptr<Model>());
    void run(const std::string& script = "", bool interactive = false,
             ext::shared_ptr<PayLog> paylog = ext::shared_ptr<PayLog>(),
             bool includePastCashflows = false);
};

} // namespace data
} // namespace ore

// %extend blocks for Pythonic interfaces

%extend ore::data::ASTNode {
    std::string toString(bool printLocationInfo = false) const {
        // Create a non-owning shared_ptr to call the free function
        QuantLib::ext::shared_ptr<ore::data::ASTNode> ptr(
            const_cast<ore::data::ASTNode*>($self), [](ore::data::ASTNode*){});
        return ore::data::to_string(ptr, printLocationInfo);
    }

    std::string __str__() const {
        QuantLib::ext::shared_ptr<ore::data::ASTNode> ptr(
            const_cast<ore::data::ASTNode*>($self), [](ore::data::ASTNode*){});
        return ore::data::to_string(ptr, false);
    }

    std::string __repr__() const {
        QuantLib::ext::shared_ptr<ore::data::ASTNode> ptr(
            const_cast<ore::data::ASTNode*>($self), [](ore::data::ASTNode*){});
        return "ASTNode(" + ore::data::to_string(ptr, false) + ")";
    }
}

%extend ore::data::Context {
    // Set a scalar Number value (deterministic, single-path)
    void setScalar(const std::string& name, double value) {
        $self->scalars[name] = QuantExt::RandomVariable(1, value);
    }

    // Set a scalar Event value (date)
    void setEvent(const std::string& name, const QuantLib::Date& date) {
        ore::data::EventVec ev;
        ev.size = 1;
        ev.value = date;
        $self->scalars[name] = ev;
    }

    // Set a scalar Currency value
    void setCurrency(const std::string& name, const std::string& ccy) {
        ore::data::CurrencyVec cv;
        cv.size = 1;
        cv.value = ccy;
        $self->scalars[name] = cv;
    }

    // Set a scalar Index value
    void setIndex(const std::string& name, const std::string& index) {
        ore::data::IndexVec iv;
        iv.size = 1;
        iv.value = index;
        $self->scalars[name] = iv;
    }

    // Set a scalar Daycounter value
    void setDaycounter(const std::string& name, const std::string& dc) {
        ore::data::DaycounterVec dv;
        dv.size = 1;
        dv.value = dc;
        $self->scalars[name] = dv;
    }

    // Mark a variable as constant (cannot be reassigned by the script)
    void markConstant(const std::string& name) {
        $self->constants.insert(name);
    }

    // Get the type (which) of a scalar variable
    int scalarWhich(const std::string& name) const {
        auto it = $self->scalars.find(name);
        if (it == $self->scalars.end())
            throw std::runtime_error("Context::scalarWhich: variable '" + name + "' not found");
        return it->second.which();
    }

    // Get a scalar Number value as a double
    double getScalar(const std::string& name) const {
        auto it = $self->scalars.find(name);
        if (it == $self->scalars.end())
            throw std::runtime_error("Context::getScalar: variable '" + name + "' not found");
        if (it->second.which() != 0)
            throw std::runtime_error("Context::getScalar: variable '" + name +
                                     "' is not a Number (which=" + std::to_string(it->second.which()) + ")");
        const QuantExt::RandomVariable& rv = boost::get<QuantExt::RandomVariable>(it->second);
        if (rv.size() == 0)
            throw std::runtime_error("Context::getScalar: variable '" + name + "' has size 0");
        return rv.at(0);
    }

    // Get a scalar Event value as a Date
    QuantLib::Date getEvent(const std::string& name) const {
        auto it = $self->scalars.find(name);
        if (it == $self->scalars.end())
            throw std::runtime_error("Context::getEvent: variable '" + name + "' not found");
        if (it->second.which() != 1)
            throw std::runtime_error("Context::getEvent: variable '" + name +
                                     "' is not an Event (which=" + std::to_string(it->second.which()) + ")");
        return boost::get<ore::data::EventVec>(it->second).value;
    }

    // Get a scalar Currency value as a string
    std::string getCurrency(const std::string& name) const {
        auto it = $self->scalars.find(name);
        if (it == $self->scalars.end())
            throw std::runtime_error("Context::getCurrency: variable '" + name + "' not found");
        if (it->second.which() != 2)
            throw std::runtime_error("Context::getCurrency: variable '" + name +
                                     "' is not a Currency (which=" + std::to_string(it->second.which()) + ")");
        return boost::get<ore::data::CurrencyVec>(it->second).value;
    }

    // Get a scalar Index value as a string
    std::string getIndex(const std::string& name) const {
        auto it = $self->scalars.find(name);
        if (it == $self->scalars.end())
            throw std::runtime_error("Context::getIndex: variable '" + name + "' not found");
        if (it->second.which() != 3)
            throw std::runtime_error("Context::getIndex: variable '" + name +
                                     "' is not an Index (which=" + std::to_string(it->second.which()) + ")");
        return boost::get<ore::data::IndexVec>(it->second).value;
    }

    // Get a scalar Daycounter value as a string
    std::string getDaycounter(const std::string& name) const {
        auto it = $self->scalars.find(name);
        if (it == $self->scalars.end())
            throw std::runtime_error("Context::getDaycounter: variable '" + name + "' not found");
        if (it->second.which() != 4)
            throw std::runtime_error("Context::getDaycounter: variable '" + name +
                                     "' is not a Daycounter (which=" + std::to_string(it->second.which()) + ")");
        return boost::get<ore::data::DaycounterVec>(it->second).value;
    }

    // Check if a scalar variable exists
    bool hasScalar(const std::string& name) const {
        return $self->scalars.find(name) != $self->scalars.end();
    }

    // Get list of all scalar variable names
    std::vector<std::string> scalarNames() const {
        std::vector<std::string> names;
        names.reserve($self->scalars.size());
        for (const auto& kv : $self->scalars)
            names.push_back(kv.first);
        return names;
    }

    // Get list of all array variable names
    std::vector<std::string> arrayNames() const {
        std::vector<std::string> names;
        names.reserve($self->arrays.size());
        for (const auto& kv : $self->arrays)
            names.push_back(kv.first);
        return names;
    }

    // Check if an array variable exists
    bool hasArray(const std::string& name) const {
        return $self->arrays.find(name) != $self->arrays.end();
    }

    // Get the size of an array variable
    Size arraySize(const std::string& name) const {
        auto it = $self->arrays.find(name);
        if (it == $self->arrays.end())
            throw std::runtime_error("Context::arraySize: array '" + name + "' not found");
        return it->second.size();
    }

    // Get a Number element from an array
    double getArrayElement(const std::string& name, Size index) const {
        auto it = $self->arrays.find(name);
        if (it == $self->arrays.end())
            throw std::runtime_error("Context::getArrayElement: array '" + name + "' not found");
        if (index >= it->second.size())
            throw std::runtime_error("Context::getArrayElement: index out of range");
        const ore::data::ValueType& v = it->second[index];
        if (v.which() != 0)
            throw std::runtime_error("Context::getArrayElement: element is not a Number");
        return boost::get<QuantExt::RandomVariable>(v).at(0);
    }

    // Set a Number element in an array (resizes if needed)
    void setArrayElement(const std::string& name, Size index, double value) {
        auto& arr = $self->arrays[name];
        if (index >= arr.size())
            arr.resize(index + 1, QuantExt::RandomVariable(1, 0.0));
        arr[index] = QuantExt::RandomVariable(1, value);
    }

    std::string __str__() const {
        std::ostringstream oss;
        oss << *$self;
        return oss.str();
    }

    std::string __repr__() const {
        std::ostringstream oss;
        oss << "Context(scalars=" << $self->scalars.size()
            << ", arrays=" << $self->arrays.size() << ")";
        return oss.str();
    }
}

%extend ore::data::ParserError {
    std::string __str__() const {
        std::ostringstream oss;
        oss << *$self;
        return oss.str();
    }
}

%extend ore::data::PayLog {
    // Get the cashflow amount at index i as a double (extracts first path)
    double amount(Size i) const {
        if (i >= $self->size())
            throw std::runtime_error("PayLog::amount: index out of range");
        const QuantExt::RandomVariable& rv = $self->amounts()[i];
        if (rv.size() == 0)
            return 0.0;
        return rv.at(0);
    }

    std::string __repr__() const {
        return "PayLog(size=" + std::to_string($self->size()) + ")";
    }
}

// Free function: pretty-print AST tree
%{
namespace ore { namespace data {
    std::string astToString(const ASTNodePtr& root, bool printLocationInfo = false) {
        return ore::data::to_string(root, printLocationInfo);
    }
    std::string printCodeContextWrapper(const std::string& script, const ASTNode* loc, bool compact = false) {
        return ore::data::printCodeContext(script, loc, compact);
    }
} }
%}

namespace ore {
namespace data {
    std::string astToString(const ext::shared_ptr<ASTNode>& root, bool printLocationInfo = false);
}
}

#if defined(SWIGPYTHON)
%pythoncode %{
def parseScript(script):
    """Parse an ORE scripting language string and return (success, ast_or_error).

    Returns a tuple (bool, ASTNode or ParserError):
      - If parsing succeeds: (True, ASTNode)
      - If parsing fails: (False, ParserError)

    Example:
        success, ast = parseScript("x = 1.0 + 2.0;")
        if success:
            print(ast.toString())
    """
    parser = ScriptParser(script)
    if parser.success():
        return (True, parser.ast())
    else:
        return (False, parser.error())
%}
#endif

#endif
