/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <qle/indexes/genericiborindex.hpp>
#include <qle/indexes/simulatedfixingsmanager.hpp>

#include <qle/indexes/ibor/all.hpp>
