/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <qle/indexes/genericiborindex.hpp>
#include <qle/indexes/fxindex.hpp>
#include <qle/indexes/inflationindexwrapper.hpp>
#include <qle/indexes/inflationindexobserver.hpp>

#include <qle/indexes/ibor/all.hpp>
