/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#ifdef BOOST_MSVC
#  include <ored/auto_link.hpp>
#endif

#include <ored/version.hpp>

#include <ored/marketdata/all.hpp>
#include <ored/portfolio/all.hpp>
#include <ored/utilities/all.hpp>
#include <ored/configuration/all.hpp>
#include <ored/model/all.hpp>
#include <ored/report/all.hpp>
