/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <qle/processes/gsrprocess.hpp>
#include <qle/processes/gsrprocesscore.hpp>

