/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <qle/methods/multipathgenerator.hpp>
#include <qle/methods/multipathgeneratorbase.hpp>

