/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <qle/termstructures/interpolateddiscountcurve.hpp>
#include <qle/termstructures/averageoisratehelper.hpp>
#include <qle/termstructures/basistwoswaphelper.hpp>
#include <qle/termstructures/crossccybasisswaphelper.hpp>
#include <qle/termstructures/fxforwardhelper.hpp>
#include <qle/termstructures/oisratehelper.hpp>
#include <qle/termstructures/tenorbasisswaphelper.hpp>

