/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <qle/instruments/averageois.hpp>
#include <qle/instruments/crossccybasisswap.hpp>
#include <qle/instruments/crossccyswap.hpp>
#include <qle/instruments/currencyswap.hpp>
#include <qle/instruments/deposit.hpp>
#include <qle/instruments/equityforward.hpp>
#include <qle/instruments/fxforward.hpp>
#include <qle/instruments/makeaverageois.hpp>
#include <qle/instruments/oibasisswap.hpp>
#include <qle/instruments/oiccbasisswap.hpp>
#include <qle/instruments/tenorbasisswap.hpp>
#include <qle/instruments/subperiodsswap.hpp>
#include <qle/instruments/creditdefaultswap.hpp>
#include <qle/instruments/makecds.hpp>
#include <qle/instruments/cdsoption.hpp>
#include <qle/instruments/payment.hpp>

