/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#ifdef BOOST_MSVC
#  include <qle/auto_link.hpp>
#endif


#include <qle/currencies/all.hpp>
#include <qle/indexes/all.hpp>
#include <qle/quotes/all.hpp>
