ARG fedora_tag=40
FROM fedora:${fedora_tag} as orebuild

MAINTAINER Quaternion Risk Management
LABEL Description="Fedora-based multi-stage container definition for ORE"

ARG build_jobs=
ARG cmake_build_type=Release

# orebuild
COPY CMakeLists.txt /ore/CMakeLists.txt
COPY QuantLib /ore/QuantLib
COPY QuantExt /ore/QuantExt
COPY OREData /ore/OREData
COPY OREAnalytics /ore/OREAnalytics
COPY App /ore/App
COPY ThirdPartyLibs /ore/ThirdPartyLibs
COPY ORETest /ore/ORETest
COPY cmake /ore/cmake

# Install dependencies
RUN yum -q -y clean expire-cache && yum -q -y update && yum -q -y install \
    boost-devel \
    bzip2-devel \
    cmake \
    gcc \
    gcc-c++ \
    glibc-devel \
    ninja-build \
    ocl-icd-devel \
    opencl-headers \
    zlib-ng-compat-devel

# set up the build
RUN cd / \
  && mkdir -p build_ore && cd build_ore \
  && cmake /ore -GNinja -DCMAKE_BUILD_TYPE=${cmake_build_type} -DORE_BUILD_DOC=OFF -DORE_USE_ZLIB=ON -DQL_ENABLE_SESSIONS=ON -DORE_ENABLE_OPENCL=ON

# build
RUN cd /build_ore \
  && cmake --build . -- -j${build_jobs:-$(nproc)} install

RUN ldconfig


# ore
FROM fedora-minimal:${fedora_tag} as ore

# Ideally, we'd take a static binary from the first stage and just copy that in - this is arguably over-inclusive
COPY --from=orebuild /usr/local/include /usr/local/include
COPY --from=orebuild /usr/local/lib/ /usr/local/lib
COPY --from=orebuild /usr/local/bin/ /usr/local/bin
COPY --from=orebuild /ore /ore
COPY --from=orebuild /usr/lib64 /usr/lib64

RUN ldconfig

CMD bash