ARG debian_tag
FROM debian:${debian_tag}

MAINTAINER Quaternion Risk Management
LABEL Description="Provide a base environment for building in C++ with Boost"

RUN apt-get update && apt-get upgrade -y \
 && apt-get install -f -y build-essential wget libbz2-dev autoconf libtool dos2unix cmake zlib1g-dev opencl-headers ocl-icd-opencl-dev \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

ARG boost_version
ARG boost_dir
ARG boost_variant=release
ARG num_cores

RUN wget http://downloads.sourceforge.net/project/boost/boost/${boost_version}/${boost_dir}.tar.gz \
    && tar xfz ${boost_dir}.tar.gz \
    && rm ${boost_dir}.tar.gz \
    && cd ${boost_dir} \
    && ./bootstrap.sh \
    && ./b2 --without-python -j ${num_cores} link=shared runtime-link=shared variant=${boost_variant} install \
    && cd .. \
    && rm -rf ${boost_dir} \
    && ldconfig

CMD bash
