# syntax = docker/dockerfile:1.2
ARG DEBIAN_TAG
FROM ${DOCKER_TAG}debian:${DEBIAN_TAG}

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive \
  apt-get install -y --no-install-recommends \
    build-essential \
    libbz2-dev \
    autoconf \
    libtool \
    cmake \
    ninja-build \
    zlib1g-dev \
    opencl-headers \
    ocl-icd-opencl-dev \
    libboost-all-dev \
    doxygen \
    graphviz \
    ccache \
    libeigen3-dev \
    clang \
    swig \
    lld \
    python3-dev \
    python3-pip \
    python3-venv \
    curl \
    -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* \
  && mv /usr/bin/ld /usr/bin/ld.backup \
  && ln -s /usr/bin/lld /usr/bin/ld

RUN \
curl -sSL https://get.docker.com -o install-docker.sh && \
sh install-docker.sh --version 28

RUN python3 -m venv /venv
ENV PATH="/venv/bin:$PATH"

RUN \
pip3 install twine cibuildwheel==3.2.1 && \
rm -rf ~/.cache/pip

