ARG DEBIAN_TAG
ARG DOCKER_REPO
FROM ${DOCKER_REPO}docker:cli as docker-cli
FROM ${DOCKER_REPO}debian:${DEBIAN_TAG}

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
  ca-certificates dos2unix gnupg python3 python3-pip python3-venv python3-dev libxml2-utils xsltproc curl git \
  -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" \
  && update-ca-certificates \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

COPY --from=docker-cli /usr/local/bin/docker /usr/local/bin/

# Create and activate virtual environment
RUN python3 -m venv /venv
ENV PATH="/venv/bin:$PATH"

# Install Python packages inside the virtual environment
RUN pip3 install --break-system-packages \
    matplotlib==3.10.9 pandas==2.3.3 pytest==9.0.3 pytest-xdist==3.8.0 pytest-timeout==2.4.0 pytest-rerunfailures==16.3 datacompy==0.19.5 jsondiff==2.2.1 lxml==6.1.1 jupyter==1.1.1 xmldiff==2.7.0 numpy==2.4.3 scipy==1.17.1 ipywidgets==8.1.8 papermill==2.7.0 python-dotenv==1.2.2 requests==2.34.2 xmlschema==4.3.1 clang-format==22.1.5 openpyxl==3.1.5 \
    && rm -rf ~/.cache/pip

CMD bash
