#ARG TEST_TAG=latest
ARG CMAKE_BUILD_TYPE=Release
ARG ORE_HELPER_VERSION
ARG ORE_VERSION

FROM ${DOCKER_REPO}env_ore:${ORE_VERSION} as env_ore
FROM ${DOCKER_REPO}ore-helper:${ORE_HELPER_VERSION}

RUN mkdir -p /ore/App

COPY --from=env_ore /usr/local/bin /ore/App
RUN true
COPY --from=env_ore /usr/local/lib /usr/local/lib
COPY --from=env_ore /usr/include/boost/ /usr/include/boost
COPY --from=env_ore /oreswig /oreswig

WORKDIR /ore

ENV PYTHONPATH=/oreswig/pythonlib
ENV LD_LIBRARY_PATH=/usr/local/lib:./

CMD bash
