# syntax = nexus3.acadiasoft.net:4445/docker/dockerfile:experimental
ARG quantlib_version=${QL_TAG}
FROM env_quantlib:${quantlib_version}

MAINTAINER Quaternion Risk Management
LABEL Description="Build ORE and add to the QuantLib build environment"

# Argument for number of cores to use while building
ARG num_cores

# install Eigen
RUN apt-get install -f -y libeigen3-dev

# Copy ORE sources for libs and app
COPY QuantExt /ore/QuantExt
COPY OREData /ore/OREData
COPY OREAnalytics /ore/OREAnalytics
COPY App /ore/App
COPY ThirdPartyLibs /ore/ThirdPartyLibs
COPY ORETest /ore/ORETest
COPY cmake /ore/cmake
COPY Docker /ore/Docker

# Need the dos2unix all if building from Windows because the shell 
# scripts fail if there are CRLF present in the files
RUN cd /ore \
  && find -regex ".*\.\(sh\|in\|ac\|am\)" -exec dos2unix {} ';' \
  && cp Docker/CMakeLists_ORE.txt CMakeLists.txt \
  && mkdir -p build.ore && cd build.ore \
  && cmake .. -DORE_BUILD_DOC=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-mavx2" -DORE_ENABLE_PARALLEL_UNIT_TEST_RUNNER=ON

WORKDIR /ore/build.ore
RUN --mount=type=cache,target=/ccache/ make -j ${num_cores} \
  && make install \
  && make doc_quantext 2>&1 | grep -v "ignoring unsupported tag" \
  && make doc_ored 2>&1 | grep -v "ignoring unsupported tag" \
  && make doc_orea 2>&1 | grep -v "ignoring unsupported tag" 
  
WORKDIR / 
RUN mkdir -p html \
  && mkdir /html/ored && cp -r /ore/OREData/doc/html/* /html/ored \
  && mkdir /html/orea && cp -r /ore/OREAnalytics/doc/html/* /html/orea \
  && mkdir /html/qle && cp -r /ore/QuantExt/doc/html/* /html/qle \
  && rm -rf ore

CMD bash
