ARG DOCKER_REPO
ARG ORE_BUILD_VERSION
FROM ${DOCKER_REPO}ore-build-dependencies:${ORE_BUILD_VERSION}

ARG WHEEL_ARCH
ARG WHEEL_IMAGE
ARG WHEELS_VERSION

ENV PATH="/venv/bin:$PATH"

ENV CIBW_BUILD="cp310-manylinux_${WHEEL_ARCH} cp312-manylinux_${WHEEL_ARCH}"
ENV CIBW_MANYLINUX_X86_64_IMAGE=${WHEEL_IMAGE}
ENV CIBW_MANYLINUX_AARCH64_IMAGE=${WHEEL_IMAGE}
# The SWIG wrapper .cpp and pre-built .o files are baked into the wheel image
# by Dockerfile-Wheels-ORE at /ore-swig-prebuilt/. CIBW_BEFORE_ALL copies them
# into the project directory so setup.py can find them.
ENV CIBW_BEFORE_ALL="echo '=== Checking /ore-swig-prebuilt ===' && ls -la /ore-swig-prebuilt/ && /opt/python/cp310-cp310/bin/pip3 install setuptools && cp /ore-swig-prebuilt/oreanalytics_wrap.cpp /project/ORE-SWIG/oreanalytics_wrap.cpp && mkdir -p /project/ORE-SWIG/.prebuilt && cp -r /ore-swig-prebuilt/linux-* /project/ORE-SWIG/.prebuilt/ && chmod +x /project/ORE-SWIG/Wheels-gitlab/oreanalytics-config && cp /project/ORE-SWIG/Wheels-gitlab/oreanalytics-config /project/ORE-SWIG/oreanalytics-config"
ENV CIBW_BEFORE_BUILD="pip install setuptools"
ENV CIBW_ENVIRONMENT="ORE_PREBUILT_DIR=/project/ORE-SWIG/.prebuilt"

WORKDIR /builds/qs/oreplus/ore
RUN \
python ../ore/Docker/update_version_number.py -f setup.py -v ${WHEELS_VERSION} && \
cibuildwheel --output-dir wheelhouse ORE-SWIG

COPY wheelhouse /wheelhouse


