
ARG WHEEL_IMG
FROM ${WHEEL_IMG}

RUN \
curl -O -L https://github.com/boostorg/boost/releases/download/boost-1.83.0/boost-1.83.0.tar.gz && \
tar xfz boost-1.83.0.tar.gz && \
cd boost-1.83.0 && \
./bootstrap.sh --with-libraries=date_time,iostreams,log,regex,serialization,system,thread,timer && \
./b2 install

