ARG boost_version=latest
FROM build_env_boost_debug:${boost_version}

MAINTAINER Quaternion Risk Management
LABEL Description="Build debug version of QuantLib and add to the Boost build environment"

# Argument for number of cores to use while building
ARG num_cores

# Exclusions are performed by .dockerignore
COPY QuantLib /lib_src/QuantLib

# Need the dos2unix all if building from Windows because the shell 
# scripts fail if there are CRLF present in the files
RUN cd /lib_src/QuantLib \
  && find -regex ".*\.\(sh\|in\|ac\|am\)" -exec dos2unix {} ';' \
  && mkdir -p build.ql && cd build.ql \
  && cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_STANDARD=11 -DCMAKE_CXX_FLAGS="-D BOOST_ENABLE_ASSERT_HANDLER" -DQL_ENABLE_SESSIONS=ON \
  && make -j ${num_cores} \
  && make install \
  && cd / \
  && rm -rf /lib_src/QuantLib/build.ql \
  && ldconfig

CMD bash
