ARG quantlib_version=latest
FROM env_quantlib_debug:${quantlib_version}

MAINTAINER Quaternion Risk Management
LABEL Description="Build debug version of ORE and add to the QuantLib build environment"

# Argument for number of cores to use while building
ARG num_cores

# Copy ORE sources for libs and app
COPY QuantExt /lib_src/QuantExt
COPY OREData /lib_src/OREData
COPY OREAnalytics /lib_src/OREAnalytics
COPY App /lib_src/App
COPY ThirdPartyLibs /lib_src/ThirdPartyLibs
COPY ORETest /lib_src/ORETest
COPY cmake /lib_src/cmake
COPY Docker /lib_src/Docker

# Need the dos2unix all if building from Windows because the shell 
# scripts fail if there are CRLF present in the files
RUN cd /lib_src \
  && find -regex ".*\.\(sh\|in\|ac\|am\)" -exec dos2unix {} ';' \
  && cp Docker/CMakeLists_ORE.txt CMakeLists.txt \
  && mkdir -p build.ore && cd build.ore \
  && cmake .. -DORE_BUILD_DOC=OFF -DCMAKE_BUILD_TYPE=Debug \
  && make -j ${num_cores} \
  && make install \
  && cd / \
  && rm -rf /lib_src/build.ore \
  && rm -rf /lib_src/App \
  && rm -rf /lib_src/cmake \
  && rm -rf /lib_src/Docker

CMD bash
