FROM blang/latex:ubuntu

MAINTAINER Quaternion Risk Management
LABEL Description="Update blang/latex:ubuntu to use newest version of latexmk."

RUN cd / \
 && apt-get update && apt-get upgrade -y \
 && apt-get install -f -y wget \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* \
 && wget https://www.cantab.net/users/johncollins/software/latexmk-jcc/latexmk-469a.zip \
 && unzip latexmk-469a.zip \
 && rm -f latexmk-469a.zip \
 && mv /usr/bin/latexmk /usr/bin/latexmk_base \
 && cp latexmk/latexmk.pl /usr/bin/latexmk \
 && cd /data

CMD bash

