
ARG WHEEL_IMG
FROM ${WHEEL_IMG}

ARG SCCACHE_VERSION=v0.14.0

RUN \
curl -O -L https://github.com/boostorg/boost/releases/download/boost-1.83.0/boost-1.83.0.tar.gz && \
tar xfz boost-1.83.0.tar.gz && \
cd boost-1.83.0 && \
./bootstrap.sh --with-libraries=date_time,iostreams,log,regex,serialization,system,thread,timer && \
./b2 install

# Install sccache from GitHub releases (matches Dockerfile-ORE-Dependencies)
RUN set -eux \
  && ARCH=$(uname -m) \
  && SCCACHE_TARBALL="sccache-${SCCACHE_VERSION}-${ARCH}-unknown-linux-musl.tar.gz" \
  && SCCACHE_URL="https://github.com/mozilla/sccache/releases/download/${SCCACHE_VERSION}/${SCCACHE_TARBALL}" \
  && curl -fsSL "${SCCACHE_URL}" -o "/tmp/${SCCACHE_TARBALL}" \
  && curl -fsSL "${SCCACHE_URL}.sha256" -o "/tmp/${SCCACHE_TARBALL}.sha256" \
  && cd /tmp && echo "$(cat ${SCCACHE_TARBALL}.sha256)  ${SCCACHE_TARBALL}" | sha256sum -c - \
  && tar -xzf "/tmp/${SCCACHE_TARBALL}" -C /tmp \
  && mv "/tmp/sccache-${SCCACHE_VERSION}-${ARCH}-unknown-linux-musl/sccache" /usr/local/bin/sccache \
  && chmod +x /usr/local/bin/sccache \
  && rm -rf /tmp/sccache-*

