ARG DOCKER_REPO
ARG ORE_BUILD_VERSION
FROM ${DOCKER_REPO}ore-build-dependencies:${ORE_BUILD_VERSION}

ARG WHEEL_ARCH
ARG WHEEL_IMAGE
ARG WHEELS_VERSION

ENV PATH="/venv/bin:$PATH"

ENV CIBW_BUILD="cp310-manylinux_${WHEEL_ARCH} cp312-manylinux_${WHEEL_ARCH}"
ENV CIBW_MANYLINUX_X86_64_IMAGE=${WHEEL_IMAGE}
ENV CIBW_MANYLINUX_AARCH64_IMAGE=${WHEEL_IMAGE}
ENV CIBW_BEFORE_ALL="/opt/python/cp310-cp310/bin/pip3 install setuptools docker && chmod +x ORE-SWIG/Wheels-gitlab/before_all_linux.sh && PATH=/opt/python/cp310-cp310/bin:$PATH ORE-SWIG/Wheels-gitlab/before_all_linux.sh"
ENV CIBW_BEFORE_BUILD="pip install setuptools"
ENV CIBW_ENVIRONMENT="PATH=/usr/lib64/ccache:/usr/lib/ccache:$PATH CCACHE_DIR=/project/.ccache CCACHE_MAXSIZE=5G"

WORKDIR /builds/qs/oreplus/ore
RUN \
python ../ore/Docker/update_version_number.py -f setup.py -v ${WHEELS_VERSION} && \
cibuildwheel --output-dir wheelhouse ORE-SWIG

COPY wheelhouse /wheelhouse


