ARG ORE_VERSION
ARG ORE_HELPER_VERSION
FROM ${DOCKER_REPO}env_oreswig:${ORE_VERSION} as env_oreswig
FROM ${DOCKER_REPO}ore-helper:${ORE_HELPER_VERSION}

RUN pip3 install --break-system-packages jupyter xmldiff numpy scipy ipywidgets && \
    rm -rf ~/.cache/pip

WORKDIR /
RUN mkdir /oreswig
RUN mkdir /oreswig/pythonlib

COPY --from=env_oreswig /oreswig/ORE.py /oreswig/pythonlib/ORE.py 
COPY --from=env_oreswig /oreswig/_OREP.so /oreswig/pythonlib/_OREP.so
COPY --from=env_oreswig /usr/lib/x86_64-linux-gnu /usr/lib/x86_64-linux-gnu
RUN true
COPY --from=env_oreswig /usr/local/lib /usr/local/lib

ENV PYTHONPATH=/oreswig/pythonlib
ENV LD_LIBRARY_PATH=/usr/local/lib

# Set env variable to run the ore examples with the python interface instead of the executable
ENV ORE_EXAMPLES_USE_PYTHON=1

CMD bash
