# syntax = nexus3.acadiasoft.net:4445/docker/dockerfile:experimental
ARG ore_version=latest
FROM env_ore:${ore_version}

MAINTAINER Quaternion Risk Management
LABEL Description="Build OREPlus"

# Install SWIG and python3
RUN apt-get update && apt-get upgrade -y \
  && apt-get install -f -y swig python3-dev clang \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /swig

COPY ore/cmake ./cmake
COPY ore/ORE-SWIG/CMakeLists.txt ./ORE-SWIG/CMakeLists.txt
#COPY ore/ORE-SWIG/__init__.py ./ORE-SWIG/__init__.py
COPY ore/ORE-SWIG/Examples ./ORE-SWIG/Examples
COPY ore/ORE-SWIG/test ./ORE-SWIG/test
COPY ore/ORE-SWIG/OREAnalytics-SWIG ./ORE-SWIG/OREAnalytics-SWIG
COPY ore/ORE-SWIG/OREData-SWIG ./ORE-SWIG/OREData-SWIG
COPY ore/ORE-SWIG/QuantExt-SWIG ./ORE-SWIG/QuantExt-SWIG
COPY ore/ORE-SWIG/QuantLib-SWIG ./ORE-SWIG/QuantLib-SWIG

#ENV PYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/ \
#    PYTHON_INCLUDE_DIR=/usr/include/x86_64-linux-gnu/python3.9

RUN find -regex ".*\.\(sh\|in\|ac\|am\)" -exec dos2unix {} ';'
WORKDIR /swig/ORE-SWIG
RUN mkdir build.release
WORKDIR /swig/ORE-SWIG/build.release
RUN cmake -Wno-dev .. -GNinja -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DORE_ENABLE_OPENCL=ON
RUN cmake --build . --config Release
WORKDIR /
RUN mkdir oreswig
RUN mv /swig/ORE-SWIG/build.release/ORE.py oreswig \
  && mv /swig/ORE-SWIG/build.release/_OREP.so oreswig

ENV PYTHONPATH=/oreswig

WORKDIR /swig/Examples