ARG ORE_VERSION
ARG ORE_BUILD_VERSION

FROM ${DOCKER_REPO}env_ore:${ORE_VERSION} as env_ore

ARG NUM_CORES

MAINTAINER Quaternion Risk Management
LABEL Description="Build OREPlus"

#COPY --from=env_ore /usr/lib/x86_64-linux-gnu /usr/lib/x86_64-linux-gnu
#COPY --from=env_ore /usr/local/lib /usr/local/lib
#COPY --from=env_ore /usr/local/include /usr/local/include

# Install SWIG and python3
RUN apt-get update && apt-get upgrade -y \
  && apt-get install -f -y swig python3-dev cmake ninja-build clang\
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /swig

COPY ore/cmake ./cmake
COPY ore/ORE-SWIG/CMakeLists.txt ./ORE-SWIG/CMakeLists.txt
COPY ore/ORE-SWIG/test ./ORE-SWIG/test
COPY ore/ORE-SWIG/OREAnalytics-SWIG ./ORE-SWIG/OREAnalytics-SWIG
COPY ore/ORE-SWIG/OREData-SWIG ./ORE-SWIG/OREData-SWIG
COPY ore/ORE-SWIG/QuantExt-SWIG ./ORE-SWIG/QuantExt-SWIG
COPY ore/ORE-SWIG/QuantLib-SWIG ./ORE-SWIG/QuantLib-SWIG

RUN find -regex ".*\.\(sh\|in\|ac\|am\)" -exec dos2unix {} ';'
WORKDIR /swig/ORE-SWIG
RUN mkdir build.release
WORKDIR /swig/ORE-SWIG/build.release
RUN cmake -Wno-dev .. -GNinja -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DORE_ENABLE_OPENCL=ON
RUN cmake --build . --config Release -- -j ${NUM_CORES}
WORKDIR /
RUN mkdir oreswig
RUN mv /swig/ORE-SWIG/build.release/ORE.py oreswig \
  && mv /swig/ORE-SWIG/build.release/_OREP.so oreswig

ENV PYTHONPATH=/oreswig

ARG DEBIAN_TAG
FROM ${DOCKER_REPO}debian:${DEBIAN_TAG}

COPY --from=env_oreswig /usr/lib/x86_64-linux-gnu /usr/lib/x86_64-linux-gnu
COPY --from=env_oreswig /usr/local/lib /usr/local/lib
COPY --from=env_oreswig /usr/local/include /usr/local/include
COPY --from=env_oreswig /usr/local/bin/ /usr/local/bin
WORKDIR /
RUN mkdir oreswig
COPY --from=env_oreswig /oreswig /oreswig

RUN ldconfig
	
CMD bash
