/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <orea/scenario/aggregationscenariodata.hpp>
#include <orea/scenario/scenariosimmarketparameters.hpp>
#include <orea/scenario/scenario.hpp>
#include <orea/scenario/scenariofactory.hpp>
#include <orea/scenario/simplescenariofactory.hpp>
#include <orea/scenario/simplescenario.hpp>
#include <orea/scenario/scenariogenerator.hpp>
#include <orea/scenario/lgmscenariogenerator.hpp>
#include <orea/scenario/crossassetmodelscenariogenerator.hpp>
#include <orea/scenario/scenariosimmarketparameters.hpp>
#include <orea/scenario/scenariosimmarket.hpp>
#include <orea/scenario/scenariogeneratordata.hpp>
#include <orea/scenario/scenariogeneratorbuilder.hpp>
#include <orea/scenario/scenariowriter.hpp>
#include <orea/scenario/shiftscenariogenerator.hpp>
#include <orea/scenario/sensitivityscenariodata.hpp>
#include <orea/scenario/sensitivityscenariogenerator.hpp>
#include <orea/scenario/stressscenariodata.hpp>
#include <orea/scenario/stressscenariogenerator.hpp>

