/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <orea/aggregation/collateralaccount.hpp>
#include <orea/aggregation/collatexposurehelper.hpp>
#include <orea/aggregation/postprocess.hpp>
