ARG python_version=3.7-rc-slim
FROM python:${python_version}


# Working directory
WORKDIR /app

# Copy needed files
COPY oreApi.py restapi.py entrypoint-restapi.sh ./

RUN pip install urllib3==1.26.7 &&\
    pip install --upgrade pip &&\
    pip install flask &&\
    pip install open-source-risk-engine &&\
    pip install pandas &&\
    pip install requests &&\
    mkdir -p Input &&\
    mkdir -p Output

EXPOSE 3001/tcp

ENTRYPOINT [ "/bin/bash", "/app/entrypoint-restapi.sh" ]
