/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <qle/pricingengines/discountingfxforwardengine.hpp>
#include <qle/pricingengines/crossccyswapengine.hpp>

