/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <orea/cube/npvcube.hpp>
#include <orea/cube/inmemorycube.hpp>
#include <orea/cube/cubewriter.hpp>
