/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <qle/calendars/philippines.hpp>
#include <qle/calendars/thailand.hpp>
#include <qle/calendars/colombia.hpp>
#include <qle/calendars/peru.hpp>
#include <qle/calendars/malaysia.hpp>
#include <qle/calendars/chile.hpp>

