# Function: write_file_if_different
# Arguments:
#   OUTPUT_FILE  - path to the file to write
#   FILE_CONTENT - the new content to write
# Description:
#   If OUTPUT_FILE does not exist, the CONTENT is written. If OUTPUT_FILE does 
#   exist, the CONTENT is written only if it differs from the existing file 
#   content.
function(write_file_if_different OUTPUT_FILE FILE_CONTENT)
    # If the file doesn't exist, write it immediately
    if(NOT EXISTS "${OUTPUT_FILE}")
        file(WRITE "${OUTPUT_FILE}" "${FILE_CONTENT}")
        message(DEBUG "File created: ${OUTPUT_FILE}")
        return()
    endif()

    # File exists, read its current content
    file(READ "${OUTPUT_FILE}" CURRENT_CONTENT)

    # Compare and write only if different
    if(NOT "${CURRENT_CONTENT}" STREQUAL "${FILE_CONTENT}")
        file(WRITE "${OUTPUT_FILE}" "${FILE_CONTENT}")
        message(DEBUG "Updated file: ${OUTPUT_FILE}")
    else()
        message(DEBUG "File unchanged: ${OUTPUT_FILE}")
    endif()
endfunction()

# function to build an "all.hpp" header that includes all the headers from a library
#
# Inputs:
#   dir - the base directory name, e.g. "qle"
#   output - the output file name, e.g. "quantext.hpp"
#   autoLink - the name of the auto link file, that only gets included on windows
#   headers - list of all headers, relative to ${dir}
function(writeAll dir output autoLink headers)
  list(REMOVE_ITEM headers "${output}")
  list(REMOVE_ITEM headers "${autoLink}")
  list(SORT headers)
  set(content "// Autogenerated by cmake\n")
  set(content "${content}// Do not edit\n")
  set(content "${content}\n")
  set(content "${content}#if !defined(BOOST_ALL_NO_LIB) && defined(BOOST_MSVC)\n")
  set(content "${content}#include <${dir}/${autoLink}>\n")
  set(content "${content}#endif\n")
  set(content "${content}\n")
  foreach(file ${headers})
    set(content "${content}#include <${dir}/${file}>\n")
    get_filename_component(extension ${file} EXT)
    if(NOT "${extension}" STREQUAL ".hpp" AND NOT "${extension}" STREQUAL ".h")
      message(FATAL_ERROR "${file} does not end on hpp or h, this can not be written to ${output}")
    endif()
  endforeach(file)
  write_file_if_different(${output} ${content})
endfunction()
