# function to build a "main.cpp" file for the test suite
#
# Inputs:
#   output - the file to be written out
function(writeTestSuiteMain output)
  file(WRITE  ${output} "// Autogenerated by cmake\n")
  file(APPEND ${output} "#ifdef BOOST_TEST_DYN_LINK\n")
  file(APPEND ${output} "#include <boost/test/unit_test.hpp>\n")
  file(APPEND ${output} "#include <boost/test/framework.hpp>\n")
  file(APPEND ${output} "using namespace boost::unit_test;\n")
  file(APPEND ${output} "test_suite* init_unit_test_suite(int, char* []);\n")
  file(APPEND ${output} "bool init_function() {\n")
  file(APPEND ${output} "framework::master_test_suite().add(init_unit_test_suite(0,0));\n")
  file(APPEND ${output} "return true;\n")
  file(APPEND ${output} "}\n")
  file(APPEND ${output} "int main( int argc, char* argv[] ) {\n")
  file(APPEND ${output} "return ::boost::unit_test::unit_test_main( &init_function, argc, argv );\n")
  file(APPEND ${output} "}\n")
  file(APPEND ${output} "#endif\n")

endfunction()
