# function to build an "all.hpp" header that includes all the headers from a library
#
# Inputs:
#   dir - the base directory name, e.g. "qle"
#   output - the output file name, e.g. "quantext.hpp"
#   autoLink - the name of the auto link file, that only gets included on windows
#   headers - list of all headers, relative to ${dir}
function(writeAll dir output autoLink headers)
  list(REMOVE_ITEM headers "${output}")
  list(REMOVE_ITEM headers "${autoLink}")
  list(SORT headers)
  set(content "// Autogenerated by cmake\n")
  set(content "${content}// Do not edit\n")
  set(content "${content}\n")
  set(content "${content}#ifdef BOOST_MSVC\n")
  set(content "${content}#include <${dir}/${autoLink}>\n")
  set(content "${content}#endif\n")
  set(content "${content}\n")
  foreach(file ${headers})
    set(content "${content}#include <${dir}/${file}>\n")
    get_filename_component(extension ${file} EXT)
    if(NOT "${extension}" STREQUAL ".hpp" AND NOT "${extension}" STREQUAL ".h")
      message(FATAL_ERROR "${file} does not end on hpp or h, this can not be written to ${output}")
    endif()
  endforeach(file)
  file(WRITE ${output} ${content})
endfunction()
