/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <orea/app/reportwriter.hpp>
#include <orea/app/parameters.hpp>
#include <orea/app/oreapp.hpp>
#include <orea/app/sensitivityrunner.hpp>
