/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ored/report/report.hpp>
#include <ored/report/inmemoryreport.hpp>
#include <ored/report/csvreport.hpp>

