use ORE

INSERT PricingEngineProducts (Model,Engine,type) VALUES ('DiscountedCashflows','DiscountingSwapEngineOptimised','Swap')
INSERT PricingEngineProducts (Model,Engine,type) VALUES ('DiscountedCashflows','DiscountingCrossCurrencySwapEngine','CrossCurrencySwap')
INSERT PricingEngineProducts (Model,Engine,type) VALUES ('DiscountedCashflows','DiscountingFxForwardEngine','FxForward')
INSERT PricingEngineProducts (Model,Engine,type) VALUES ('GarmanKohlhagen','AnalyticEuropeanEngine','FxOption')
INSERT PricingEngineProducts (Model,Engine,type) VALUES ('BlackBachelier','BlackBachelierSwaptionEngine','EuropeanSwaption')
INSERT PricingEngineProducts (Model,Engine,type) VALUES ('LGM','Grid','BermudanSwaption')
INSERT PricingEngineEngineParameters (Parameter,name,type) VALUES (3.0,'sy','BermudanSwaption')
INSERT PricingEngineEngineParameters (Parameter,name,type) VALUES (10,'ny','BermudanSwaption')
INSERT PricingEngineEngineParameters (Parameter,name,type) VALUES (3.0,'sx','BermudanSwaption')
INSERT PricingEngineEngineParameters (Parameter,name,type) VALUES (10,'nx','BermudanSwaption')
INSERT PricingEngineModelParameters (Parameter,name,type) VALUES ('Bootstrap','Calibration','BermudanSwaption')
INSERT PricingEngineModelParameters (Parameter,name,type) VALUES ('CoterminalATM','CalibrationStrategy','BermudanSwaption')
INSERT PricingEngineModelParameters (Parameter,name,type) VALUES (0.03,'Reversion','BermudanSwaption')
INSERT PricingEngineModelParameters (Parameter,name,type) VALUES ('HullWhite','ReversionType','BermudanSwaption')
INSERT PricingEngineModelParameters (Parameter,name,type) VALUES (0.01,'Volatility','BermudanSwaption')
INSERT PricingEngineModelParameters (Parameter,name,type) VALUES ('Hagan','VolatilityType','BermudanSwaption')
INSERT PricingEngineModelParameters (Parameter,name,type) VALUES (0.0001,'Tolerance','BermudanSwaption')
INSERT PricingEngineProducts (Model,Engine,type) VALUES ('IborCapModel','IborCapEngine','CapFloor')
INSERT PricingEngineProducts (Model,Engine,type) VALUES ('BlackOrBachelier','BlackIborCouponPricer','CapFlooredIborLeg')
INSERT PricingEngineProducts (Model,Engine,type) VALUES ('DiscountedCashflows','DiscountingEquityForwardEngine','EquityForward')
INSERT PricingEngineProducts (Model,Engine,type) VALUES ('BlackScholesMerton','AnalyticEuropeanEngine','EquityOption')
INSERT PricingEngineProducts (Model,Engine,type) VALUES ('DiscountedCashflows','DiscountingRiskyBondEngine','Bond')
INSERT PricingEngineEngineParameters (Parameter,name,type) VALUES ('6M','TimestepPeriod','Bond')
