/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ored/model/crossassetmodeldata.hpp>
#include <ored/model/crossassetmodelbuilder.hpp>
#include <ored/model/fxbsdata.hpp>
#include <ored/model/fxbsbuilder.hpp>
#include <ored/model/lgmdata.hpp>
#include <ored/model/lgmbuilder.hpp>
#include <ored/model/utilities.hpp>
