ARG python_version=3.7-rc-slim
FROM python:${python_version}

# Working directory
WORKDIR /app

# Copy needed files
COPY simplefileserver.py entrypoint-simplefileserver.sh ./

RUN pip install --upgrade pip &&\
    pip install flask &&\
    mkdir -p Input &&\
    mkdir -p Output


EXPOSE 3000/tcp

ENTRYPOINT [ "/bin/bash", "/app/entrypoint-simplefileserver.sh" ]
